//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMoreTryWPF.SessionService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class AccessDeniedFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class createSessionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class createSessionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tinField;
        
        private long projectCodeField;
        
        private bool projectCodeFieldSpecified;
        
        private businessProfileType businessProfileTypeField;
        
        private bool businessProfileTypeFieldSpecified;
        
        private string x509CertificateField;
        
        private SourceType sourceTypeField;
        
        private bool sourceTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
                this.RaisePropertyChanged("tin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long projectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
                this.RaisePropertyChanged("projectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectCodeSpecified {
            get {
                return this.projectCodeFieldSpecified;
            }
            set {
                this.projectCodeFieldSpecified = value;
                this.RaisePropertyChanged("projectCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public businessProfileType businessProfileType {
            get {
                return this.businessProfileTypeField;
            }
            set {
                this.businessProfileTypeField = value;
                this.RaisePropertyChanged("businessProfileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessProfileTypeSpecified {
            get {
                return this.businessProfileTypeFieldSpecified;
            }
            set {
                this.businessProfileTypeFieldSpecified = value;
                this.RaisePropertyChanged("businessProfileTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string x509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
                this.RaisePropertyChanged("x509Certificate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public SourceType sourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("sourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sourceTypeSpecified {
            get {
                return this.sourceTypeFieldSpecified;
            }
            set {
                this.sourceTypeFieldSpecified = value;
                this.RaisePropertyChanged("sourceTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public enum businessProfileType {
        
        /// <remarks/>
        ADMIN_ENTERPRISE,
        
        /// <remarks/>
        USER,
        
        /// <remarks/>
        ENTREPRENEUR,
        
        /// <remarks/>
        ENTREPRENEUR_USER,
        
        /// <remarks/>
        INDIVIDUAL,
        
        /// <remarks/>
        LAWYER,
        
        /// <remarks/>
        BAILIFF,
        
        /// <remarks/>
        MEDIATOR,
        
        /// <remarks/>
        NOTARY,
        
        /// <remarks/>
        LAWYER_USER,
        
        /// <remarks/>
        BAILIFF_USER,
        
        /// <remarks/>
        MEDIATOR_USER,
        
        /// <remarks/>
        NOTARY_USER,
        
        /// <remarks/>
        PROJECT_ADMIN,
        
        /// <remarks/>
        PROJECT_USER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public enum SourceType {
        
        /// <remarks/>
        BROWSER,
        
        /// <remarks/>
        DESKTOP,
        
        /// <remarks/>
        ERP_1C,
        
        /// <remarks/>
        ERP_SAP,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class closeSessionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sessionStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sessionStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public enum sessionStatus {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        CLOSED,
        
        /// <remarks/>
        NOT_FOUND,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(currentUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(currentUserProfilesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(currentSessionStatusRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(closeSessionRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public abstract partial class AbstractSessionAwareRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class currentUserRequest : AbstractSessionAwareRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class currentUserProfilesRequest : AbstractSessionAwareRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class currentSessionStatusRequest : AbstractSessionAwareRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class closeSessionRequest : AbstractSessionAwareRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class BusinessFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class SessionClosedFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="esf", ConfigurationName="SessionService.SessionService")]
    public interface SessionService {
        
        // CODEGEN: Generating message contract since the operation closeSession is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        OneMoreTryWPF.SessionService.closeSessionResponse1 closeSession(OneMoreTryWPF.SessionService.closeSession request);
        
        // CODEGEN: Generating message contract since the operation createSession is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneMoreTryWPF.SessionService.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneMoreTryWPF.SessionService.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        OneMoreTryWPF.SessionService.createSessionResponse1 createSession(OneMoreTryWPF.SessionService.createSession request);
        
        // CODEGEN: Generating message contract since the operation currentSessionStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        OneMoreTryWPF.SessionService.currentSessionStatusResponse1 currentSessionStatus(OneMoreTryWPF.SessionService.currentSessionStatus request);
        
        // CODEGEN: Generating message contract since the operation currentUserProfiles is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneMoreTryWPF.SessionService.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        OneMoreTryWPF.SessionService.currentUserProfilesResponse1 currentUserProfiles(OneMoreTryWPF.SessionService.currentUserProfiles request);
        
        // CODEGEN: Generating message contract since the operation currentUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneMoreTryWPF.SessionService.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        OneMoreTryWPF.SessionService.currentUserResponse1 currentUser(OneMoreTryWPF.SessionService.currentUser request);
        
        // CODEGEN: Generating message contract since the operation closeSessionByCredentials is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneMoreTryWPF.SessionService.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(OneMoreTryWPF.SessionService.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        OneMoreTryWPF.SessionService.closeSessionByCredentialsResponse closeSessionByCredentials(OneMoreTryWPF.SessionService.closeSessionByCredentials request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.closeSessionRequest closeSessionRequest;
        
        public closeSession() {
        }
        
        public closeSession(OneMoreTryWPF.SessionService.closeSessionRequest closeSessionRequest) {
            this.closeSessionRequest = closeSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSessionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.closeSessionResponse closeSessionResponse;
        
        public closeSessionResponse1() {
        }
        
        public closeSessionResponse1(OneMoreTryWPF.SessionService.closeSessionResponse closeSessionResponse) {
            this.closeSessionResponse = closeSessionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.createSessionRequest createSessionRequest;
        
        public createSession() {
        }
        
        public createSession(OneMoreTryWPF.SessionService.createSessionRequest createSessionRequest) {
            this.createSessionRequest = createSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createSessionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.createSessionResponse createSessionResponse;
        
        public createSessionResponse1() {
        }
        
        public createSessionResponse1(OneMoreTryWPF.SessionService.createSessionResponse createSessionResponse) {
            this.createSessionResponse = createSessionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class currentSessionStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sessionStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sessionStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentSessionStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.currentSessionStatusRequest currentSessionStatusRequest;
        
        public currentSessionStatus() {
        }
        
        public currentSessionStatus(OneMoreTryWPF.SessionService.currentSessionStatusRequest currentSessionStatusRequest) {
            this.currentSessionStatusRequest = currentSessionStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentSessionStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.currentSessionStatusResponse currentSessionStatusResponse;
        
        public currentSessionStatusResponse1() {
        }
        
        public currentSessionStatusResponse1(OneMoreTryWPF.SessionService.currentSessionStatusResponse currentSessionStatusResponse) {
            this.currentSessionStatusResponse = currentSessionStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class currentUserProfilesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private profileInfo[] profileInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public profileInfo[] profileInfoList {
            get {
                return this.profileInfoListField;
            }
            set {
                this.profileInfoListField = value;
                this.RaisePropertyChanged("profileInfoList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class profileInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iinField;
        
        private string tinField;
        
        private businessProfileType businessProfileTypeField;
        
        private bool businessProfileTypeFieldSpecified;
        
        private userStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private profileType typeField;
        
        private bool typeFieldSpecified;
        
        private projectParticipantType projectParticipantTypeField;
        
        private bool projectParticipantTypeFieldSpecified;
        
        private long projectCodeField;
        
        private bool projectCodeFieldSpecified;
        
        private string projectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string iin {
            get {
                return this.iinField;
            }
            set {
                this.iinField = value;
                this.RaisePropertyChanged("iin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
                this.RaisePropertyChanged("tin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public businessProfileType businessProfileType {
            get {
                return this.businessProfileTypeField;
            }
            set {
                this.businessProfileTypeField = value;
                this.RaisePropertyChanged("businessProfileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessProfileTypeSpecified {
            get {
                return this.businessProfileTypeFieldSpecified;
            }
            set {
                this.businessProfileTypeFieldSpecified = value;
                this.RaisePropertyChanged("businessProfileTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public userStatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public profileType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public projectParticipantType projectParticipantType {
            get {
                return this.projectParticipantTypeField;
            }
            set {
                this.projectParticipantTypeField = value;
                this.RaisePropertyChanged("projectParticipantType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectParticipantTypeSpecified {
            get {
                return this.projectParticipantTypeFieldSpecified;
            }
            set {
                this.projectParticipantTypeFieldSpecified = value;
                this.RaisePropertyChanged("projectParticipantTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long projectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
                this.RaisePropertyChanged("projectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectCodeSpecified {
            get {
                return this.projectCodeFieldSpecified;
            }
            set {
                this.projectCodeFieldSpecified = value;
                this.RaisePropertyChanged("projectCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string projectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
                this.RaisePropertyChanged("projectName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public enum userStatusType {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        BLOCKED,
        
        /// <remarks/>
        ENTERPRISE_ADMIN_CHANGE_BLOCKED,
        
        /// <remarks/>
        ENTERPRISE_BLOCKED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public enum profileType {
        
        /// <remarks/>
        GENERAL,
        
        /// <remarks/>
        PROJECT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public enum projectParticipantType {
        
        /// <remarks/>
        ATTORNEY,
        
        /// <remarks/>
        OPERATOR,
        
        /// <remarks/>
        TRUSTER,
        
        /// <remarks/>
        CONTRACTOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUserProfiles {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.currentUserProfilesRequest currentUserProfilesRequest;
        
        public currentUserProfiles() {
        }
        
        public currentUserProfiles(OneMoreTryWPF.SessionService.currentUserProfilesRequest currentUserProfilesRequest) {
            this.currentUserProfilesRequest = currentUserProfilesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUserProfilesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.currentUserProfilesResponse currentUserProfilesResponse;
        
        public currentUserProfilesResponse1() {
        }
        
        public currentUserProfilesResponse1(OneMoreTryWPF.SessionService.currentUserProfilesResponse currentUserProfilesResponse) {
            this.currentUserProfilesResponse = currentUserProfilesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class currentUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private User userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string emailField;
        
        private string mobileField;
        
        private string issueDateField;
        
        private string issuedByField;
        
        private string passportNumField;
        
        private userStatusType statusField;
        
        private string reasonField;
        
        private Taxpayer taxpayerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("issueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string issuedBy {
            get {
                return this.issuedByField;
            }
            set {
                this.issuedByField = value;
                this.RaisePropertyChanged("issuedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string passportNum {
            get {
                return this.passportNumField;
            }
            set {
                this.passportNumField = value;
                this.RaisePropertyChanged("passportNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public userStatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Taxpayer taxpayer {
            get {
                return this.taxpayerField;
            }
            set {
                this.taxpayerField = value;
                this.RaisePropertyChanged("taxpayer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class Taxpayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tinField;
        
        private string nameRuField;
        
        private string lastNameRuField;
        
        private string firstNameRuField;
        
        private string middleNameRuField;
        
        private string lastNameKzField;
        
        private string firstNameKzField;
        
        private string middleNameKzField;
        
        private string nameKzField;
        
        private string addressRuField;
        
        private string addressKzField;
        
        private string certificateSeriesField;
        
        private string certificateNumField;
        
        private bool residentField;
        
        private Taxpayer headOfficeField;
        
        private EnterpriseType typeField;
        
        private bool typeFieldSpecified;
        
        private bool resourceUserField;
        
        private SettlementAccount[] accountsField;
        
        private string enterpriseAdministratorField;
        
        private string budgetIinField;
        
        private string kogdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
                this.RaisePropertyChanged("tin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nameRu {
            get {
                return this.nameRuField;
            }
            set {
                this.nameRuField = value;
                this.RaisePropertyChanged("nameRu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lastNameRu {
            get {
                return this.lastNameRuField;
            }
            set {
                this.lastNameRuField = value;
                this.RaisePropertyChanged("lastNameRu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string firstNameRu {
            get {
                return this.firstNameRuField;
            }
            set {
                this.firstNameRuField = value;
                this.RaisePropertyChanged("firstNameRu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string middleNameRu {
            get {
                return this.middleNameRuField;
            }
            set {
                this.middleNameRuField = value;
                this.RaisePropertyChanged("middleNameRu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lastNameKz {
            get {
                return this.lastNameKzField;
            }
            set {
                this.lastNameKzField = value;
                this.RaisePropertyChanged("lastNameKz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string firstNameKz {
            get {
                return this.firstNameKzField;
            }
            set {
                this.firstNameKzField = value;
                this.RaisePropertyChanged("firstNameKz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string middleNameKz {
            get {
                return this.middleNameKzField;
            }
            set {
                this.middleNameKzField = value;
                this.RaisePropertyChanged("middleNameKz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nameKz {
            get {
                return this.nameKzField;
            }
            set {
                this.nameKzField = value;
                this.RaisePropertyChanged("nameKz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string addressRu {
            get {
                return this.addressRuField;
            }
            set {
                this.addressRuField = value;
                this.RaisePropertyChanged("addressRu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string addressKz {
            get {
                return this.addressKzField;
            }
            set {
                this.addressKzField = value;
                this.RaisePropertyChanged("addressKz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string certificateSeries {
            get {
                return this.certificateSeriesField;
            }
            set {
                this.certificateSeriesField = value;
                this.RaisePropertyChanged("certificateSeries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string certificateNum {
            get {
                return this.certificateNumField;
            }
            set {
                this.certificateNumField = value;
                this.RaisePropertyChanged("certificateNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool resident {
            get {
                return this.residentField;
            }
            set {
                this.residentField = value;
                this.RaisePropertyChanged("resident");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public Taxpayer headOffice {
            get {
                return this.headOfficeField;
            }
            set {
                this.headOfficeField = value;
                this.RaisePropertyChanged("headOffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public EnterpriseType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public bool resourceUser {
            get {
                return this.resourceUserField;
            }
            set {
                this.resourceUserField = value;
                this.RaisePropertyChanged("resourceUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("settlementAccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SettlementAccount[] accounts {
            get {
                return this.accountsField;
            }
            set {
                this.accountsField = value;
                this.RaisePropertyChanged("accounts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string enterpriseAdministrator {
            get {
                return this.enterpriseAdministratorField;
            }
            set {
                this.enterpriseAdministratorField = value;
                this.RaisePropertyChanged("enterpriseAdministrator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string budgetIin {
            get {
                return this.budgetIinField;
            }
            set {
                this.budgetIinField = value;
                this.RaisePropertyChanged("budgetIin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string kogd {
            get {
                return this.kogdField;
            }
            set {
                this.kogdField = value;
                this.RaisePropertyChanged("kogd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public enum EnterpriseType {
        
        /// <remarks/>
        NOT_SET,
        
        /// <remarks/>
        INDIVIDUAL,
        
        /// <remarks/>
        INDIVIDUAL_ENTREPRENEUR,
        
        /// <remarks/>
        PRIVATE_ENTERPRISE,
        
        /// <remarks/>
        STATE_ENTERPRISE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class SettlementAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string taxpayerTinField;
        
        private Bank bankField;
        
        private int accountTypeField;
        
        private bool accountTypeFieldSpecified;
        
        private string accountField;
        
        private System.DateTime dateOpenField;
        
        private bool dateOpenFieldSpecified;
        
        private System.DateTime dateCloseField;
        
        private bool dateCloseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string taxpayerTin {
            get {
                return this.taxpayerTinField;
            }
            set {
                this.taxpayerTinField = value;
                this.RaisePropertyChanged("taxpayerTin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Bank bank {
            get {
                return this.bankField;
            }
            set {
                this.bankField = value;
                this.RaisePropertyChanged("bank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int accountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("accountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountTypeSpecified {
            get {
                return this.accountTypeFieldSpecified;
            }
            set {
                this.accountTypeFieldSpecified = value;
                this.RaisePropertyChanged("accountTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime dateOpen {
            get {
                return this.dateOpenField;
            }
            set {
                this.dateOpenField = value;
                this.RaisePropertyChanged("dateOpen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateOpenSpecified {
            get {
                return this.dateOpenFieldSpecified;
            }
            set {
                this.dateOpenFieldSpecified = value;
                this.RaisePropertyChanged("dateOpenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime dateClose {
            get {
                return this.dateCloseField;
            }
            set {
                this.dateCloseField = value;
                this.RaisePropertyChanged("dateClose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCloseSpecified {
            get {
                return this.dateCloseFieldSpecified;
            }
            set {
                this.dateCloseFieldSpecified = value;
                this.RaisePropertyChanged("dateCloseSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class Bank : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameRuField;
        
        private string nameKzField;
        
        private string bikField;
        
        private string codeField;
        
        private string tinField;
        
        private string rnnField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nameRu {
            get {
                return this.nameRuField;
            }
            set {
                this.nameRuField = value;
                this.RaisePropertyChanged("nameRu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nameKz {
            get {
                return this.nameKzField;
            }
            set {
                this.nameKzField = value;
                this.RaisePropertyChanged("nameKz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bik {
            get {
                return this.bikField;
            }
            set {
                this.bikField = value;
                this.RaisePropertyChanged("bik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
                this.RaisePropertyChanged("tin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string rnn {
            get {
                return this.rnnField;
            }
            set {
                this.rnnField = value;
                this.RaisePropertyChanged("rnn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.currentUserRequest currentUserRequest;
        
        public currentUser() {
        }
        
        public currentUser(OneMoreTryWPF.SessionService.currentUserRequest currentUserRequest) {
            this.currentUserRequest = currentUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.currentUserResponse currentUserResponse;
        
        public currentUserResponse1() {
        }
        
        public currentUserResponse1(OneMoreTryWPF.SessionService.currentUserResponse currentUserResponse) {
            this.currentUserResponse = currentUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class closeSessionByCredentialsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tinField;
        
        private long projectCodeField;
        
        private bool projectCodeFieldSpecified;
        
        private businessProfileType businessProfileTypeField;
        
        private bool businessProfileTypeFieldSpecified;
        
        private string x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
                this.RaisePropertyChanged("tin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long projectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
                this.RaisePropertyChanged("projectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectCodeSpecified {
            get {
                return this.projectCodeFieldSpecified;
            }
            set {
                this.projectCodeFieldSpecified = value;
                this.RaisePropertyChanged("projectCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public businessProfileType businessProfileType {
            get {
                return this.businessProfileTypeField;
            }
            set {
                this.businessProfileTypeField = value;
                this.RaisePropertyChanged("businessProfileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessProfileTypeSpecified {
            get {
                return this.businessProfileTypeFieldSpecified;
            }
            set {
                this.businessProfileTypeFieldSpecified = value;
                this.RaisePropertyChanged("businessProfileTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string x509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
                this.RaisePropertyChanged("x509Certificate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSessionByCredentials {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.closeSessionByCredentialsRequest closeSessionByCredentialsRequest;
        
        public closeSessionByCredentials() {
        }
        
        public closeSessionByCredentials(OneMoreTryWPF.SessionService.closeSessionByCredentialsRequest closeSessionByCredentialsRequest) {
            this.closeSessionByCredentialsRequest = closeSessionByCredentialsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSessionByCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SessionService.closeSessionResponse closeSessionResponse;
        
        public closeSessionByCredentialsResponse() {
        }
        
        public closeSessionByCredentialsResponse(OneMoreTryWPF.SessionService.closeSessionResponse closeSessionResponse) {
            this.closeSessionResponse = closeSessionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionServiceChannel : OneMoreTryWPF.SessionService.SessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionServiceClient : System.ServiceModel.ClientBase<OneMoreTryWPF.SessionService.SessionService>, OneMoreTryWPF.SessionService.SessionService {
        
        public SessionServiceClient() {
        }
        
        public SessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SessionService.closeSessionResponse1 OneMoreTryWPF.SessionService.SessionService.closeSession(OneMoreTryWPF.SessionService.closeSession request) {
            return base.Channel.closeSession(request);
        }
        
        public OneMoreTryWPF.SessionService.closeSessionResponse closeSession(OneMoreTryWPF.SessionService.closeSessionRequest closeSessionRequest) {
            OneMoreTryWPF.SessionService.closeSession inValue = new OneMoreTryWPF.SessionService.closeSession();
            inValue.closeSessionRequest = closeSessionRequest;
            OneMoreTryWPF.SessionService.closeSessionResponse1 retVal = ((OneMoreTryWPF.SessionService.SessionService)(this)).closeSession(inValue);
            return retVal.closeSessionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SessionService.createSessionResponse1 OneMoreTryWPF.SessionService.SessionService.createSession(OneMoreTryWPF.SessionService.createSession request) {
            return base.Channel.createSession(request);
        }
        
        public OneMoreTryWPF.SessionService.createSessionResponse createSession(OneMoreTryWPF.SessionService.createSessionRequest createSessionRequest) {
            OneMoreTryWPF.SessionService.createSession inValue = new OneMoreTryWPF.SessionService.createSession();
            inValue.createSessionRequest = createSessionRequest;
            OneMoreTryWPF.SessionService.createSessionResponse1 retVal = ((OneMoreTryWPF.SessionService.SessionService)(this)).createSession(inValue);
            return retVal.createSessionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SessionService.currentSessionStatusResponse1 OneMoreTryWPF.SessionService.SessionService.currentSessionStatus(OneMoreTryWPF.SessionService.currentSessionStatus request) {
            return base.Channel.currentSessionStatus(request);
        }
        
        public OneMoreTryWPF.SessionService.currentSessionStatusResponse currentSessionStatus(OneMoreTryWPF.SessionService.currentSessionStatusRequest currentSessionStatusRequest) {
            OneMoreTryWPF.SessionService.currentSessionStatus inValue = new OneMoreTryWPF.SessionService.currentSessionStatus();
            inValue.currentSessionStatusRequest = currentSessionStatusRequest;
            OneMoreTryWPF.SessionService.currentSessionStatusResponse1 retVal = ((OneMoreTryWPF.SessionService.SessionService)(this)).currentSessionStatus(inValue);
            return retVal.currentSessionStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SessionService.currentUserProfilesResponse1 OneMoreTryWPF.SessionService.SessionService.currentUserProfiles(OneMoreTryWPF.SessionService.currentUserProfiles request) {
            return base.Channel.currentUserProfiles(request);
        }
        
        public OneMoreTryWPF.SessionService.currentUserProfilesResponse currentUserProfiles(OneMoreTryWPF.SessionService.currentUserProfilesRequest currentUserProfilesRequest) {
            OneMoreTryWPF.SessionService.currentUserProfiles inValue = new OneMoreTryWPF.SessionService.currentUserProfiles();
            inValue.currentUserProfilesRequest = currentUserProfilesRequest;
            OneMoreTryWPF.SessionService.currentUserProfilesResponse1 retVal = ((OneMoreTryWPF.SessionService.SessionService)(this)).currentUserProfiles(inValue);
            return retVal.currentUserProfilesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SessionService.currentUserResponse1 OneMoreTryWPF.SessionService.SessionService.currentUser(OneMoreTryWPF.SessionService.currentUser request) {
            return base.Channel.currentUser(request);
        }
        
        public OneMoreTryWPF.SessionService.currentUserResponse currentUser(OneMoreTryWPF.SessionService.currentUserRequest currentUserRequest) {
            OneMoreTryWPF.SessionService.currentUser inValue = new OneMoreTryWPF.SessionService.currentUser();
            inValue.currentUserRequest = currentUserRequest;
            OneMoreTryWPF.SessionService.currentUserResponse1 retVal = ((OneMoreTryWPF.SessionService.SessionService)(this)).currentUser(inValue);
            return retVal.currentUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SessionService.closeSessionByCredentialsResponse OneMoreTryWPF.SessionService.SessionService.closeSessionByCredentials(OneMoreTryWPF.SessionService.closeSessionByCredentials request) {
            return base.Channel.closeSessionByCredentials(request);
        }
        
        public OneMoreTryWPF.SessionService.closeSessionResponse closeSessionByCredentials(OneMoreTryWPF.SessionService.closeSessionByCredentialsRequest closeSessionByCredentialsRequest) {
            OneMoreTryWPF.SessionService.closeSessionByCredentials inValue = new OneMoreTryWPF.SessionService.closeSessionByCredentials();
            inValue.closeSessionByCredentialsRequest = closeSessionByCredentialsRequest;
            OneMoreTryWPF.SessionService.closeSessionByCredentialsResponse retVal = ((OneMoreTryWPF.SessionService.SessionService)(this)).closeSessionByCredentials(inValue);
            return retVal.closeSessionResponse;
        }
    }
}
