//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMoreTryWPF.SignatureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="esf", ConfigurationName="SignatureService.LocalService")]
    public interface LocalService {
        
        // CODEGEN: Generating message contract since the operation signIdWithReasonList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        OneMoreTryWPF.SignatureService.signIdWithReasonListResponse signIdWithReasonList(OneMoreTryWPF.SignatureService.signIdWithReasonList request);
        
        // CODEGEN: Generating message contract since the operation generateDocumentSignature is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        OneMoreTryWPF.SignatureService.generateDocumentSignatureResponse generateDocumentSignature(OneMoreTryWPF.SignatureService.generateDocumentSignature request);
        
        // CODEGEN: Generating message contract since the operation signIdList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        OneMoreTryWPF.SignatureService.signIdListResponse signIdList(OneMoreTryWPF.SignatureService.signIdList request);
        
        // CODEGEN: Generating message contract since the operation generateSignature is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        OneMoreTryWPF.SignatureService.generateSignatureResponse generateSignature(OneMoreTryWPF.SignatureService.generateSignature request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class ListWithReasonSignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InvoiceIdWithReason[] idsWithReasonsField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("idWithReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InvoiceIdWithReason[] idsWithReasons {
            get {
                return this.idsWithReasonsField;
            }
            set {
                this.idsWithReasonsField = value;
                this.RaisePropertyChanged("idsWithReasons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class InvoiceIdWithReason : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class invoiceHash : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hashField;
        
        private string invoiceNumField;
        
        private string signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string invoiceNum {
            get {
                return this.invoiceNumField;
            }
            set {
                this.invoiceNumField = value;
                this.RaisePropertyChanged("invoiceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class SignatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private invoiceHash[] invoiceHashListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public invoiceHash[] invoiceHashList {
            get {
                return this.invoiceHashListField;
            }
            set {
                this.invoiceHashListField = value;
                this.RaisePropertyChanged("invoiceHashList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class SignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] invoiceBodiesField;
        
        private string versionField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("invoiceBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] invoiceBodies {
            get {
                return this.invoiceBodiesField;
            }
            set {
                this.invoiceBodiesField = value;
                this.RaisePropertyChanged("invoiceBodies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class ListSignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] idsField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public long[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
                this.RaisePropertyChanged("ids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class DocumentSignatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signedDataField;
        
        private string signatureField;
        
        private string certificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string signedData {
            get {
                return this.signedDataField;
            }
            set {
                this.signedDataField = value;
                this.RaisePropertyChanged("signedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
                this.RaisePropertyChanged("certificate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class DocumentSignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signableDataField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string signableData {
            get {
                return this.signableDataField;
            }
            set {
                this.signableDataField = value;
                this.RaisePropertyChanged("signableData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class ListSignatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signatureField;
        
        private string hashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdWithReasonList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.ListWithReasonSignatureRequest idWithReasonListRequest;
        
        public signIdWithReasonList() {
        }
        
        public signIdWithReasonList(OneMoreTryWPF.SignatureService.ListWithReasonSignatureRequest idWithReasonListRequest) {
            this.idWithReasonListRequest = idWithReasonListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdWithReasonListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.ListSignatureResponse listSignatureResponse;
        
        public signIdWithReasonListResponse() {
        }
        
        public signIdWithReasonListResponse(OneMoreTryWPF.SignatureService.ListSignatureResponse listSignatureResponse) {
            this.listSignatureResponse = listSignatureResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateDocumentSignature {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.DocumentSignatureRequest documentSignatureRequest;
        
        public generateDocumentSignature() {
        }
        
        public generateDocumentSignature(OneMoreTryWPF.SignatureService.DocumentSignatureRequest documentSignatureRequest) {
            this.documentSignatureRequest = documentSignatureRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateDocumentSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.DocumentSignatureResponse documentSignatureResponse;
        
        public generateDocumentSignatureResponse() {
        }
        
        public generateDocumentSignatureResponse(OneMoreTryWPF.SignatureService.DocumentSignatureResponse documentSignatureResponse) {
            this.documentSignatureResponse = documentSignatureResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.ListSignatureRequest idListRequest;
        
        public signIdList() {
        }
        
        public signIdList(OneMoreTryWPF.SignatureService.ListSignatureRequest idListRequest) {
            this.idListRequest = idListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.ListSignatureResponse listSignatureResponse;
        
        public signIdListResponse() {
        }
        
        public signIdListResponse(OneMoreTryWPF.SignatureService.ListSignatureResponse listSignatureResponse) {
            this.listSignatureResponse = listSignatureResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateSignature {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.SignatureRequest signatureRequest;
        
        public generateSignature() {
        }
        
        public generateSignature(OneMoreTryWPF.SignatureService.SignatureRequest signatureRequest) {
            this.signatureRequest = signatureRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OneMoreTryWPF.SignatureService.SignatureResponse signatureResponse;
        
        public generateSignatureResponse() {
        }
        
        public generateSignatureResponse(OneMoreTryWPF.SignatureService.SignatureResponse signatureResponse) {
            this.signatureResponse = signatureResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocalServiceChannel : OneMoreTryWPF.SignatureService.LocalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalServiceClient : System.ServiceModel.ClientBase<OneMoreTryWPF.SignatureService.LocalService>, OneMoreTryWPF.SignatureService.LocalService {
        
        public LocalServiceClient() {
        }
        
        public LocalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SignatureService.signIdWithReasonListResponse OneMoreTryWPF.SignatureService.LocalService.signIdWithReasonList(OneMoreTryWPF.SignatureService.signIdWithReasonList request) {
            return base.Channel.signIdWithReasonList(request);
        }
        
        public OneMoreTryWPF.SignatureService.ListSignatureResponse signIdWithReasonList(OneMoreTryWPF.SignatureService.ListWithReasonSignatureRequest idWithReasonListRequest) {
            OneMoreTryWPF.SignatureService.signIdWithReasonList inValue = new OneMoreTryWPF.SignatureService.signIdWithReasonList();
            inValue.idWithReasonListRequest = idWithReasonListRequest;
            OneMoreTryWPF.SignatureService.signIdWithReasonListResponse retVal = ((OneMoreTryWPF.SignatureService.LocalService)(this)).signIdWithReasonList(inValue);
            return retVal.listSignatureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SignatureService.generateDocumentSignatureResponse OneMoreTryWPF.SignatureService.LocalService.generateDocumentSignature(OneMoreTryWPF.SignatureService.generateDocumentSignature request) {
            return base.Channel.generateDocumentSignature(request);
        }
        
        public OneMoreTryWPF.SignatureService.DocumentSignatureResponse generateDocumentSignature(OneMoreTryWPF.SignatureService.DocumentSignatureRequest documentSignatureRequest) {
            OneMoreTryWPF.SignatureService.generateDocumentSignature inValue = new OneMoreTryWPF.SignatureService.generateDocumentSignature();
            inValue.documentSignatureRequest = documentSignatureRequest;
            OneMoreTryWPF.SignatureService.generateDocumentSignatureResponse retVal = ((OneMoreTryWPF.SignatureService.LocalService)(this)).generateDocumentSignature(inValue);
            return retVal.documentSignatureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SignatureService.signIdListResponse OneMoreTryWPF.SignatureService.LocalService.signIdList(OneMoreTryWPF.SignatureService.signIdList request) {
            return base.Channel.signIdList(request);
        }
        
        public OneMoreTryWPF.SignatureService.ListSignatureResponse signIdList(OneMoreTryWPF.SignatureService.ListSignatureRequest idListRequest) {
            OneMoreTryWPF.SignatureService.signIdList inValue = new OneMoreTryWPF.SignatureService.signIdList();
            inValue.idListRequest = idListRequest;
            OneMoreTryWPF.SignatureService.signIdListResponse retVal = ((OneMoreTryWPF.SignatureService.LocalService)(this)).signIdList(inValue);
            return retVal.listSignatureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneMoreTryWPF.SignatureService.generateSignatureResponse OneMoreTryWPF.SignatureService.LocalService.generateSignature(OneMoreTryWPF.SignatureService.generateSignature request) {
            return base.Channel.generateSignature(request);
        }
        
        public OneMoreTryWPF.SignatureService.SignatureResponse generateSignature(OneMoreTryWPF.SignatureService.SignatureRequest signatureRequest) {
            OneMoreTryWPF.SignatureService.generateSignature inValue = new OneMoreTryWPF.SignatureService.generateSignature();
            inValue.signatureRequest = signatureRequest;
            OneMoreTryWPF.SignatureService.generateSignatureResponse retVal = ((OneMoreTryWPF.SignatureService.LocalService)(this)).generateSignature(inValue);
            return retVal.signatureResponse;
        }
    }
}
